language: c
sudo: required
dist: trusty
notifications:
  irc: "irc.freenode.net#haskell-raaz"
fast_finish: true
before_install:
  - sudo apt-get update
  - sudo apt-get install coq coq-theories
  - coqtop --version
  - coq_makefile -f _CoqProject -o Makefile
script:
  - make
after_success:
  - echo "All is well."
after_failure:
  - echo "Build failed."
branches:
  only:
    - master
