language: c
sudo: false
addons:
  apt:
    packages:
      - coq
notifications:
  irc: "irc.freenode.net#haskell-raaz"
fast_finish: true
before_install:
script:
  - coq_makefile -f _CoqProject -o Makefile
  - make
  - make html
after_success:
  - echo "All is well."
after_failure:
  - echo "Build failed."
branches:
  only:
    - master
    - x-merge-packages
