language: c
sudo: false
addons:
  apt:
    packages:
      - ocaml
      - ocaml-nox
      - ocaml-base-nox
      - ocaml-native-compilers
      - libcoq-ocaml
      - camlp5
      - liblablgtk2-ocaml
      - coq
      - coq-doc
      - coq-theories
notifications:
  irc: "irc.freenode.net#haskell-raaz"
fast_finish: true
before_install:
  - coqtop --version
  - coq_makefile -f _CoqProject -o Makefile
script:
  - make
  - make html
after_success:
  - echo "All is well."
after_failure:
  - echo "Build failed."
branches:
  only:
    - master
    - x-merge-packages
